# Dependencies
markdown:         redcarpet
redcarpet:    
    extensions:   ["tables", "no_intra_emphasis"]
highligher:       pygments
encoding: utf-8
# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Phillip Hetzel
tagline:          'Data Addict, Hot Sauce Enthusiast'
description:      'Data analytics for those of us who were not Computer Science majors'
url:              phetzel1.github.io
baseurl:          

author:
  name:           'Phillip Hetzel'
  url:            www.linkedin.com/in/philliphetzel

github:
  repo:           https://github.com/phetzel1

linkedin:
   link:         http://www.linkedin.com/in/philliphetzel


categories:  [projects, posts]