# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'Data Addict, Late-Blooming Coder, Hot Sauce Enthusiast'
description:      'Please poke around this website to get a feel for my work!'
url:              http://phetzel1.github.io
baseurl:          /

author:
  name:           'Phillip Hetzel'
  url:            https://twitter.com/PJPretzel

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


projects:
  - {title: "Campaign Data", 
     url: "http://phetzel1.github.io/Election_Data",
    }
  - {title: "Lobbying Disclosures",
     url: "http://phetzel1.github.io/Lobbying",
    }

